### ISSUE TITLE
Nova versão

### ISSUE THREAD

**Issue by tlworkssoftware** [robsonsilv4/covid19_statistics#1]
Boa tarde, criei novas features com base no que você já havia desenvolvido, tentei criar um novo PR mas não tenho autorização, caso tenha interesse, é só me avisar.

**Comment by robsonsilv4** [comment]
Olá @tlworkssoftware, claro que sim, toda contribuição é bem vinda!

Para criar um PR, você precisa primeiro fazer um fork do projeto, então, basta realizar as modificações no seu fork e depois submetê-las na forma de um PR.

Antes de enviar o PR, lembre-se de sincronizar o repositório, para evitar assim algum conflito.

Estarei aguardando suas modificações, qualquer dúvida é só falar :)

**Comment by robsonsilv4** [comment]
Muito obrigado @tlworkssoftware, as novas funcionalidades ficaram incríveis :)
Acabei de fazer o merge e logo irei atualizar a documentação e a lista de contribuidores.
